
CREATE DATABASE IF NOT EXISTS securedoc;
USE securedoc;


CREATE TABLE users (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('user', 'admin', 'auditor') DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE files (
  id VARCHAR(36) PRIMARY KEY,
  fileName VARCHAR(255) NOT NULL,
  localUrl VARCHAR(512) NOT NULL,
  size INT NOT NULL,
  owner VARCHAR(36) NOT NULL,
  hardwarePinHash VARCHAR(255),
  created_by VARCHAR(36),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE file_access (
  id VARCHAR(36) PRIMARY KEY,
  fileId VARCHAR(36) NOT NULL,
  userId VARCHAR(36) NOT NULL,
  permission ENUM('read', 'write') NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (fileId) REFERENCES files(id),
  FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE arduino_config (
  id VARCHAR(36) PRIMARY KEY,
  consoleHash VARCHAR(255) NOT NULL,
  enabled BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
